- name: Install rofi
  apt: name={{ item }} state=present
  with_items:
    - pkg-config
    - libglib2.0-dev
    - libxkbcommon-x11-dev
    - libxinerama-dev
    - libpango1.0-dev
    - libstartup-notification0-dev
  become: yes

- name: Get rofi
  get_url: url=https://github.com/DaveDavenport/rofi/releases/download/{{ version }}/rofi-{{ version }}.tar.gz dest=/usr/src/rofi-{{ version }}.tar.gz validate_certs=False
  become: yes

- name: Unarchive rofi
  unarchive: src=/usr/src/rofi-{{ version }}.tar.gz dest=/tmp copy=no
  become: yes

- name: Build rofi
  shell: ./configure && make chdir=/tmp/rofi-{{ version }}

- name: Install rofi
  shell: make install chdir=/tmp/rofi-{{ version }}
  become: yes

- name: Clean up
  file: path=/tmp/rofi-{{ version }} state=absent
